development:
  sessions:
    default:
      database: goliath_grape_moped
      hosts:
        - localhost:27017
      options:
        pool_size:
          20

testing:
  sessions:
    default:
      database: goliath_grape_moped
      hosts:
        - localhost:27017
      options:
        pool_size:
          20

production:
  sessions:
    default:
      database: goliath_grape_moped
      hosts:
        - localhost:27017
      options:
        pool_size:
          20
